#Requires AutoHotkey v2.0

#Include ..\lib\ScriptEditor.ahk

try {
    editor := ScriptEditor(Map())
    guiObj := editor.Build()

    if !editor.HasProp("btnPickWindow")
        throw Error("Build should create a pick window button")
    if !editor.HasProp("btnRunBot")
        throw Error("Build should create a bot run button")
    if !editor.HasProp("btnTestRegionFind")
        throw Error("Build should keep a manual image-find test入口")
    if !editor.HasProp("btnTestRegionOcr")
        throw Error("Build should keep a manual OCR test入口")
    if !editor.HasProp("btnRecordClick")
        throw Error("Build should create a click recording button")
    if !editor.HasProp("btnRecordKey")
        throw Error("Build should create a keypress recording button")
    if !editor.HasProp("btnAddFindImage")
        throw Error("Build should expose a button for adding find_image steps")
    if !editor.HasProp("btnAddClickImage")
        throw Error("Build should expose a button for adding click_image steps")
    if !editor.HasProp("btnAddOcrMatch")
        throw Error("Build should expose a button for adding ocr_match steps")
    if !editor.HasProp("btnAddMoveToCoord")
        throw Error("Build should expose a button for adding move_to_coord steps")
    if !editor.HasProp("btnAddBranch")
        throw Error("Build should expose a button for adding branch steps")
    if !editor.HasProp("btnConfigureStep")
        throw Error("Build should expose a button for configuring recognition steps")
    if !editor.HasProp("btnTestMoveToCoord")
        throw Error("Build should expose a button for testing the selected move_to_coord step")
    if !editor.HasProp("btnPickMoveCenter")
        throw Error("Build should expose a button for picking the move_to_coord player center point")
    if !editor.HasProp("btnPickMoveCoordRegion")
        throw Error("Build should expose a button for picking the move_to_coord OCR region")
    if editor.HasProp("btnApplyMovePreset")
        throw Error("Build should no longer expose move_to_coord preset tooling in click-navigation mode")
    if editor.HasProp("btnCalibrateMoveSpeed")
        throw Error("Build should no longer expose move_to_coord speed calibration tooling in click-navigation mode")
    if editor.HasProp("btnDiagnoseMoveDirection")
        throw Error("Build should no longer expose move_to_coord direction diagnosis tooling in click-navigation mode")
    if editor.HasProp("btnApplyMoveDirectionAdvice")
        throw Error("Build should no longer expose move_to_coord direction advice tooling in click-navigation mode")
    if editor.HasProp("btnFlipMoveAxisX")
        throw Error("Build should no longer expose move_to_coord axis flip tooling in click-navigation mode")
    if editor.HasProp("btnFlipMoveAxisY")
        throw Error("Build should no longer expose move_to_coord axis flip tooling in click-navigation mode")
    if editor.HasProp("btnSwapMoveAxes")
        throw Error("Build should no longer expose move_to_coord axis swap tooling in click-navigation mode")
    if editor.HasProp("btnMoveScaleDown")
        throw Error("Build should no longer expose move_to_coord scale correction tooling in click-navigation mode")
    if editor.HasProp("btnMoveScaleUp")
        throw Error("Build should no longer expose move_to_coord scale correction tooling in click-navigation mode")

    guiObj.Destroy()
    ExitApp(0)
} catch {
    ExitApp(1)
}
