#Requires AutoHotkey v2.0

#Include ..\lib\StepSchema.ahk

statusPath := A_ScriptDir "\tmp_step_schema_result.txt"
if FileExist(statusPath)
    FileDelete(statusPath)

try {
    clickStep := StepSchema.CreateStep("click")
    if !clickStep.params.HasProp("repeat")
        throw Error("click should expose a repeat param for rapid clicks")
    if !clickStep.params.HasProp("intervalMs")
        throw Error("click should expose an intervalMs param for rapid clicks")
    if (clickStep.params.repeat != 1)
        throw Error("click should default repeat to 1")
    if (clickStep.params.intervalMs != 0)
        throw Error("click should default intervalMs to 0")

    step := StepSchema.CreateStep("ocr_match")
    if (step.type != "ocr_match")
        throw Error("CreateStep should preserve the requested step type")
    if (step.name = "")
        throw Error("CreateStep should generate a default step name")
    if !step.enabled
        throw Error("CreateStep should default enabled to true")
    if (step.onSuccess.action != "next")
        throw Error("CreateStep should default success action to next")
    if (step.onFailure.action != "stop")
        throw Error("CreateStep should default failure action to stop")
    if !step.HasProp("params")
        throw Error("CreateStep should initialize params")
    if !step.params.HasProp("region")
        throw Error("ocr_match should expose a default region param")

    branchStep := StepSchema.CreateStep("branch")
    if (branchStep.type != "branch")
        throw Error("CreateStep should support branch steps")
    if !branchStep.params.HasProp("conditionType")
        throw Error("branch should expose a conditionType param")
    if !branchStep.params.HasProp("region")
        throw Error("branch should expose a region param")

    mouseActionStep := StepSchema.CreateStep("mouse_action")
    if (mouseActionStep.type != "mouse_action")
        throw Error("CreateStep should support mouse_action steps")
    if (mouseActionStep.name != "按住")
        throw Error("mouse_action should use the default hold-step name")
    if !mouseActionStep.params.HasProp("action")
        throw Error("mouse_action should expose an action param")
    if !mouseActionStep.params.HasProp("holdMs")
        throw Error("mouse_action should expose a holdMs param")
    if (mouseActionStep.params.action != "hold")
        throw Error("mouse_action should default action to hold")
    if (mouseActionStep.params.holdMs != 0)
        throw Error("mouse_action should default holdMs to 0")

    moveToCoordStep := StepSchema.CreateStep("move_to_coord")
    if (moveToCoordStep.type != "move_to_coord")
        throw Error("CreateStep should support move_to_coord steps")
    if (moveToCoordStep.name != "移动到坐标")
        throw Error("move_to_coord should use the default coordinate-navigation step name")
    if !moveToCoordStep.params.HasProp("coordRegion")
        throw Error("move_to_coord should expose a coordRegion param")
    if !moveToCoordStep.params.HasProp("targetX")
        throw Error("move_to_coord should expose a targetX param")
    if !moveToCoordStep.params.HasProp("targetY")
        throw Error("move_to_coord should expose a targetY param")
    if !moveToCoordStep.params.HasProp("playerCenterX")
        throw Error("move_to_coord should expose a playerCenterX param")
    if !moveToCoordStep.params.HasProp("playerCenterY")
        throw Error("move_to_coord should expose a playerCenterY param")
    if !moveToCoordStep.params.HasProp("clickOffsetPx")
        throw Error("move_to_coord should expose a clickOffsetPx param for click-based navigation")
    if !moveToCoordStep.params.HasProp("ocrEveryClicks")
        throw Error("move_to_coord should expose an ocrEveryClicks param for periodic OCR correction")
    if !moveToCoordStep.params.HasProp("ocrRetryCount")
        throw Error("move_to_coord should expose an ocrRetryCount param for transient OCR failures")
    if !moveToCoordStep.params.HasProp("ocrRetryIntervalMs")
        throw Error("move_to_coord should expose an ocrRetryIntervalMs param for OCR retry pacing")
    if !moveToCoordStep.params.HasProp("stuckRounds")
        throw Error("move_to_coord should expose a stuckRounds param for progress-based stuck detection")
    if !moveToCoordStep.params.HasProp("tolerance")
        throw Error("move_to_coord should expose a tolerance param")
    if !moveToCoordStep.params.HasProp("timeoutMs")
        throw Error("move_to_coord should expose a timeoutMs param")
    if moveToCoordStep.params.HasProp("axisXScreenX")
        throw Error("move_to_coord should no longer expose axis-mapping params in click-navigation mode")
    if moveToCoordStep.params.HasProp("directionScale")
        throw Error("move_to_coord should no longer expose directionScale in click-navigation mode")
    if moveToCoordStep.params.HasProp("segmentCoordSpan")
        throw Error("move_to_coord should no longer expose segmentCoordSpan in click-navigation mode")
    if moveToCoordStep.params.HasProp("msPerCoord")
        throw Error("move_to_coord should no longer expose msPerCoord in click-navigation mode")
    if moveToCoordStep.params.HasProp("pollIntervalMs")
        throw Error("move_to_coord should no longer expose pollIntervalMs in click-navigation mode")
    if (moveToCoordStep.params.clickOffsetPx != 200)
        throw Error("move_to_coord should default clickOffsetPx to 200")
    if (moveToCoordStep.params.ocrEveryClicks != 6)
        throw Error("move_to_coord should default ocrEveryClicks to 6 for steadier OCR correction")
    if (moveToCoordStep.params.ocrRetryCount != 2)
        throw Error("move_to_coord should default ocrRetryCount to 2 for transient OCR failures")
    if (moveToCoordStep.params.ocrRetryIntervalMs != 150)
        throw Error("move_to_coord should default ocrRetryIntervalMs to 150")
    if (moveToCoordStep.params.stuckRounds != 3)
        throw Error("move_to_coord should default stuckRounds to 3")
    if (moveToCoordStep.params.tolerance != 1)
        throw Error("move_to_coord should default tolerance to 1")

    script := {
        steps: [
            {id: "step_1", type: "wait", name: "等待", enabled: true, params: {ms: 1000}, onSuccess: {action: "next"}, onFailure: {action: "stop"}},
            {id: "step_2", type: "ocr_match", name: "识别文字", enabled: true, params: {targetText: "开始"}, onSuccess: {action: "jump", targetStepId: "step_1"}, onFailure: {action: "jump", targetStepId: "missing"}}
        ]
    }

    err := StepSchema.ValidateJumpTargets(script)
    if !InStr(err, "missing")
        throw Error("ValidateJumpTargets should report missing jump targets")

    script.steps[2].onFailure := {action: "stop"}
    err := StepSchema.ValidateJumpTargets(script)
    if (err != "")
        throw Error("ValidateJumpTargets should allow valid jump targets")

    FileAppend("PASS", statusPath, "UTF-8")
    ExitApp(0)
} catch as err {
    FileAppend("FAIL: " err.Message, statusPath, "UTF-8")
    ExitApp(1)
}
